### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tomekichi49** [tomekichi49/furima-40920#20]
# URL
https://furima-40920.onrender.com/

# 出品者用のメールアドレスとパスワード
メールアドレス：hoge@hoge
パスワード：aaa111

# 購入者用のメールアドレスとパスワード
メールアドレス：huga@huga
パスワード：aaa111

**Comment by ghost** [comment]
@tomekichi49 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**出品機能**
- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
現在、順番が、「レディースメンズ」となっておりますので、「メンズ、レディース」という順番に修正をお願いいたします。

- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
エラーハンドリングによって出品ページに戻った時に、再度料金を入力しても販売手数料や販売利益が反映されません。修正をお願いいたします。

<img width="452" alt="スクリーンショット 2024-06-20 9 44 48" src="https://github.com/tomekichi49/furima-40920/assets/116065064/05404635-6079-4519-ad0a-8bf4c44ead3e">

**購入機能**

- [x] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
現在、カード情報が入力できない状態になっております。
入力ができるように修正をお願いいたします。
※現在、上記の理由により購入ができないため、購入をしないと確認できないものの挙動は次回ご提出時に併せて確認をさせていただきます。ご認識のほどよろしくお願いいたします。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。

https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tomekichi49** [comment]
お世話になっております！

修正が完了致しましたのでご確認のほどよろしくお願いします！

https://furima-40920.onrender.com/

**Comment by motomuun** [comment]
@tomekichi49 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品購入機能の確認**

- [x] **クレジットカード情報は必須であり、PAY.JPテストカードの情報で決済ができること**
エラーハンドリングによって購入ページに戻ると、クレジットカード情報入力欄に入力ができなくなります。何度でも入力出来るように修正をお願いします。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by tomekichi49** [comment]
お世話になっております！

修正が完了致しましたのでお手数をおかけしますが、ご確認のほどよろしくお願いします！

https://furima-40920.onrender.com/

**Comment by mo1015** [comment]
@tomekichi49 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by tomekichi49** [comment]
ありがとうございました！！
